"""Initial migration.

Revision ID: 417f9fb684f1
Revises: 52a401750a76
Create Date: 2024-07-17 16:05:14.539422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '417f9fb684f1'
down_revision = '52a401750a76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assignments', 'state',
               existing_type=sa.VARCHAR(length=9),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assignments', 'state',
               existing_type=sa.VARCHAR(length=9),
               nullable=True)
    # ### end Alembic commands ###
